[package]
name = "chutils"
version.workspace = true
edition.workspace = true

[dependencies]
tokio = { workspace = true }
clap = { workspace = true }
eyre = { workspace = true }
tracing = { workspace = true }
migration = { workspace = true, features = ["clap", "rustls-tls"] }
tracing-subscriber = { workspace = true }
ch = { workspace = true }
backup = { workspace = true, features = ["clap", "rustls-tls"] }
human_bytes = { workspace = true, features = ["fast"] }
humantime = { workspace = true }
